web/router.ex
defmodule Ticketex.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Ticketex do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    resources "/project", ProjectController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ticketex do
  #   pipe_through :api
  # end
end

lib/ticketex/endpoint.ex
defmodule Ticketex.Endpoint do
  use Phoenix.Endpoint, otp_app: :ticketex

  plug Plug.Static,
    at: "/", from: :ticketex

  plug Plug.Logger

  # Code reloading will only work if the :code_reloader key of
  # the :phoenix application is set to true in your config file.
  plug Phoenix.CodeReloader

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_ticketex_key",
    signing_salt: "rDXrij6+",
    encryption_salt: "jaoR7jbe"

  plug :router, Ticketex.Router
end

web/controllers/page_controller.ex
defmodule Ticketex.PageController do
  use Phoenix.Controller

  plug :action

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/project_controller.ex
defmodule Ticketex.ProjectController do
  use Phoenix.Controller

  plug :action

  def index(conn, _params) do
    render conn, "index.html"
  end

  def new(conn, _params) do
    render conn, "new.html"
  end
end

web/controllers/projects_controller.ex
defmodule Ticketex.ProjectsController do
  use Phoenix.Controller

  plug :action

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule Ticketex.ErrorView do
  use Ticketex.View

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  # Render all other templates as 500
  def render(_, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Ticketex.LayoutView do
  use Ticketex.View
end

web/views/page_view.ex
defmodule Ticketex.PageView do
  use Ticketex.View
end

web/views/project_view.ex
defmodule Ticketex.ProjectView do
  use Ticketex.View
end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="/css/phoenix.css">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
        </ul>
        <span class="logo"></span>
      </div>

      <%= @inner %>

      <div class="footer">
        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
      </div>

    </div> <!-- /container -->
  </body>
</html>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/issues?state=open">Issues</a>
      </li>
      <li>
        <a href="irc://irc.freenode.net/elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/chris_mccord">@chris_mccord</a>
      </li>
    </ul>
  </div>
</div>

web/templates/page/not_found.html.eex
The page you are looking for does not exist

web/templates/project/index.html.eex
<h1>Projects</h1>
<a href="<%= project_path(Endpoint, :new) %>" name="new_project">New Project</a>

web/templates/project/new.html.eex
<form method="POST" action="<%= project_path(Endpoint, :create) %>">
  <input type="text" name="project_name"/>
  <input type="submit" name="create_project" text="Create Project"/>
</form>